=== DigiscapeNoida/.Net-Projects-/XML ORDER/Validation/WileyJ-Order.dtd
<!-- Wiley Journal XML Order DTD
     For automated integration with FMS and TIS
     Version 1.0 dated May 9, 2008
     Typical invocation:
     <!DOCTYPE orders SYSTEM "WileyJ-Order.dtd">
-->

<!ENTITY % mo        "(01|02|03|04|05|06|07|08|09|10|11|12)" >
<!ENTITY % day       "(01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|
                       17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)" >
<!ENTITY % hr        "(00|01|02|03|04|05|06|07|08|09|10|11|
                       12|13|14|15|16|17|18|19|20|21|22|23)" >
<!ENTITY % ms        "(00|01|02|03|04|05|06|07|08|09|
                       10|11|12|13|14|15|16|17|18|19|
                       20|21|22|23|24|25|26|27|28|29|
                       30|31|32|33|34|35|36|37|38|39|
                       40|41|42|43|44|45|46|47|48|49|
                       50|51|52|53|54|55|56|57|58|59)" >

<!ENTITY % step               "(RSVP | CU | S5 | S100 | MCE | S200 | S300 | P100 | Q300 | S350 | F300 |
                                 S5RESUPPLY | S100RESUPPLY | S200RESUPPLY | S300RESUPPLY |
                                 P100RESUPPLY | Q300RESUPPLY | F300RESUPPLY |
                                 PRINT | OFFPRINTS | E-OFFPRINT | BIND | ISSUE-LABELS |
                                 SEND-ISSUE | SEND-OFF-SYSTEM-ISSUE | SEND-OFFPRINTS |
                                 PUBACC | PUBACCRESUPPLY)" >

<!ENTITY % exec               "( ES | PSP | AUTHOR-GATEWAY | TYPESETTER |
                                 PRINTER | BINDER | WAREHOUSE |
                                 OFFPRINTS-SENDER | PUBACC-SUPPLIER |
                                 LOGIN-SUPPLIER )" >
<!ENTITY % page-range-type    "( PRELIM | INTERIOR | EXTRA | INSERT | BACKMATTER )" >
<!ENTITY % zipcode-pos        "( NONE | BEFORECTY | AFTERCTY | BEFORECNY | AFTERCNY )" >
<!ENTITY % corrections-type   "( FTP | POST | FTPANDPOST |
                                 MASTERFTP | MASTERPOST | MASTERFTPANDPOST |
                                 MASTERREMARKS | MASTERNONE |
                                 REMARKS | NONE )">

<!ENTITY % yesno              "(yes|no)" >

<!ENTITY % customer              "(JWUSA|JWUK|JWVCH|LWW|THIEME)" >

<!-- GENERAL SUPPLIER ORDERS DTD -->

<!ELEMENT orders             ( order+ )>
<!ELEMENT order              ( time, due-date?, prod-site, stage, executor+,
                                ( item-info | issue-info | print-bind-info | 
                                  issue-labels-info ))>
<!ATTLIST order
          customer %customer;  #REQUIRED
          category (JOURNAL|BOOK) 'JOURNAL'>
<!ELEMENT time               EMPTY>
<!ATTLIST time
           day                %day;    #REQUIRED
           month              %mo;     #REQUIRED
           yr                 NMTOKEN  #REQUIRED
           hr                 %hr;     #IMPLIED
           min                %ms;     #IMPLIED
           sec                %ms;     #IMPLIED>

<!ELEMENT due-date           ( date )>
<!ELEMENT prod-site          ( #PCDATA )>
<!ELEMENT stage              EMPTY>
<!ATTLIST stage
           step               %step;   #REQUIRED>

<!ELEMENT date               EMPTY>
<!ATTLIST date
           day                %day;    #REQUIRED
           month              %mo;     #REQUIRED
           yr                 NMTOKEN  #REQUIRED> 

<!ELEMENT executor           ( exec-code, exec-name, aff? )>
<!ATTLIST executor
           type               %exec;   #REQUIRED
           addressee          %yesno;  "no">

<!ELEMENT exec-code          ( #PCDATA )>
<!ELEMENT exec-name          ( #PCDATA )>

<!ELEMENT aff                ( organization?, institute?, inst-contd?,
                                address?, address-contd?, zipcode?, cty?, cny?,
                                tel?, fax?, ead* )>
<!ELEMENT organization       ( #PCDATA )>
<!ELEMENT institute          ( #PCDATA )>
<!ELEMENT inst-contd         ( #PCDATA )>
<!ELEMENT address            ( #PCDATA )>
<!ELEMENT address-contd      ( #PCDATA )>
<!ELEMENT zipcode            ( #PCDATA )>
<!ATTLIST zipcode
           zipcode-pos        %zipcode-pos;    #IMPLIED>
<!ELEMENT cty                ( #PCDATA )>
<!ELEMENT cny                ( #PCDATA )>
<!ELEMENT tel                ( #PCDATA )>
<!ELEMENT fax                ( #PCDATA )>
<!ELEMENT ead                ( #PCDATA )>

<!-- E-COVERSHEET -->

<!ENTITY % online-version-type  "(e-only|e-extra|e-appended|print)">

<!ELEMENT item-info          ( version-no?, jid, jname, aid, pii?, doi?,
                                item-group?, item-group-description?,
                                item-title, editor-info?, received-date?,
                                revised-date?, accept-date?, expiry-date?,
                                prd-type-as-sent, online-version, pit?,
                                copy-edit-content?,typesetting-required?,copy-editing-required?, no-mns-pages, 
                                no-phys-figs, no-bw-figs?,
                                no-web-colour-figs?, no-colour-figs, no-e-components,
                                physical-figures?, e-components?, righthand-start?,
                                copyright-status?, copyright-recd-date?,
                                first-author?, corr-author?, eproofing-info?,
                                item-remarks?, corrections? )>

<!ELEMENT jid                ( #PCDATA )>
<!ELEMENT jname              ( #PCDATA )>
<!ELEMENT aid                ( #PCDATA )>
<!ELEMENT pii                ( #PCDATA )>
<!ELEMENT doi                ( #PCDATA )>
<!ELEMENT version-no         ( #PCDATA )>
<!ELEMENT batch-member       ( aid, pit, pii, doi? )>
<!ELEMENT funded-by          ( #PCDATA )>
<!ELEMENT grant-number       ( #PCDATA )>
<!ELEMENT principal-investigator  ( fnm?, snm, aff )>
<!ELEMENT item-group         ( #PCDATA )>
<!ELEMENT item-group-description  ( #PCDATA )>
<!ELEMENT item-title         ( #PCDATA )>
<!ELEMENT editor-info        ( editor, designation?, aff? )>
<!ELEMENT editor             ( #PCDATA )>
<!ELEMENT designation        ( #PCDATA )>
<!ELEMENT received-date      ( date )>
<!ELEMENT revised-date       ( date )>
<!ELEMENT accept-date        ( date )>
<!ELEMENT expiry-date        ( date )>
 
<!ELEMENT prd-type-as-sent   ( #PCDATA )>
<!ELEMENT online-version     EMPTY>
<!ATTLIST online-version
           type               %online-version-type;  'print'>
<!ELEMENT pit                ( #PCDATA )>
<!ELEMENT copy-edit-content  EMPTY>
<!ATTLIST copy-edit-content
           required           %yesno;  #REQUIRED>
<!ELEMENT copy-editing-required  EMPTY>
<!ATTLIST copy-editing-required
           required           %yesno;  #REQUIRED>
<!ELEMENT typesetting-required  EMPTY>
<!ATTLIST typesetting-required
           required           %yesno;  #REQUIRED>
<!ELEMENT no-mns-pages       ( #PCDATA )>
<!ELEMENT no-phys-figs       ( #PCDATA )>
<!ELEMENT no-bw-figs         ( #PCDATA )>
<!ELEMENT no-colour-figs     ( #PCDATA )>
<!ELEMENT no-web-colour-figs ( #PCDATA )>
<!ELEMENT no-e-components    ( #PCDATA )>

<!ELEMENT physical-figures   ( figure+ )>
<!ELEMENT figure             ( figure-nr, figure-type, figure-production-type?,
                                file-name*, figure-remarks? )>
<!ELEMENT figure-nr          ( #PCDATA )>
<!ELEMENT figure-type        ( #PCDATA )>
<!ELEMENT figure-production-type  ( #PCDATA )>
<!ELEMENT file-name          ( #PCDATA )>
<!ELEMENT figure-remarks     ( #PCDATA )>

<!ELEMENT e-components       ( e-component+ )>
<!ELEMENT e-component        ( e-component-nr, file-name*,
                                e-component-format, e-component-remarks? )>
<!ELEMENT e-component-nr     ( #PCDATA )>
<!ELEMENT e-component-format ( #PCDATA )>
<!ELEMENT e-component-remarks    ( #PCDATA )>

<!ELEMENT righthand-start    ( #PCDATA )>
<!ELEMENT copyright-status   ( #PCDATA )>
<!ELEMENT copyright-recd-date  ( date )>
<!ELEMENT first-author       ( degree?, fnm?, snm )>
<!ELEMENT degree             ( #PCDATA )>
<!ELEMENT fnm                ( #PCDATA )>
<!ELEMENT snm                ( #PCDATA )>
<!ELEMENT corr-author        ( degree?, fnm?, snm, aff )>
<!ELEMENT eproofing-info     ( to-mail*, cc-mail*, cta?, cid?, offprint?, additional-attachments* )>
<!ELEMENT to-mail            ( #PCDATA )>
<!ELEMENT cc-mail            ( #PCDATA )>
<!ELEMENT cta                ( #PCDATA )>
<!ELEMENT cid                ( #PCDATA )>
<!ELEMENT offprint           ( #PCDATA )>
<!ELEMENT additional-attachments    ( #PCDATA )>
<!ELEMENT item-remarks       ( item-remark+ )>
<!ELEMENT item-remark        ( remark-type?, remark, response? )>
<!ELEMENT remark-type        ( #PCDATA )>
<!ELEMENT remark             ( #PCDATA )>
<!ELEMENT response           ( #PCDATA )>

<!ELEMENT corrections        EMPTY>
<!ATTLIST corrections
           type               %corrections-type;    'FTP'>

<!-- ISSUE PAGINATION SHEET AND OFFPRINT SHEET -->

<!ENTITY % row-type           "(ce|non-ce|blank|remark|h1|h2|h3|h4|he|advert)">

<!ELEMENT issue-info         ( general-info, issue-content, issue-remarks? )>

<!ELEMENT general-info       ( version-no?, pii?, doi?,
                                issue-production-type,
                                buffer-status, hold-until-date?,
                                jid, journal-no, issn, journal-title, pmg?,
                                vol-from, vol-to?, iss-from?, iss-to?, supp?,
                                paper-type-interior, paper-type-cover,
                                cover-finishing, binding-type,
                                trimmed-size?, head-margin?, back-margin?,
                                typeset-model?, righthand-start?,
                                issue-weight?, spine-width?,
                                effect-cover-date?, cover-date?, cover-date-printed?,
                                special-issue?, no-pages-prelims?,
                                no-pages-interior, no-pages-extra?,
                                no-pages-insert?, no-pages-bm?,
                                no-pages-print, no-pages-web?, no-pages-total,
                                no-pages-blank, no-pages-adverts, page-ranges,
                                corrections? )>

<!ELEMENT issue-production-type  ( #PCDATA )>
<!ELEMENT buffer-status      EMPTY>
<!ATTLIST buffer-status
           status             %yesno;  #REQUIRED>
<!ELEMENT hold-until-date    ( date )>

<!ELEMENT journal-no         ( #PCDATA )>
<!ELEMENT issn               ( #PCDATA )>
<!ELEMENT journal-title      ( #PCDATA )>
<!ELEMENT pmg                ( #PCDATA )>

<!ELEMENT vol-from           ( #PCDATA )>
<!ELEMENT vol-to             ( #PCDATA )>
<!ELEMENT iss-from           ( #PCDATA )>
<!ELEMENT iss-to             ( #PCDATA )>
<!ELEMENT supp               ( #PCDATA )>

<!ELEMENT paper-type-interior  ( #PCDATA )>
<!ELEMENT paper-type-cover   ( #PCDATA )>
<!ELEMENT cover-finishing    ( #PCDATA )>
<!ELEMENT binding-type       ( #PCDATA )>
<!ELEMENT trimmed-size       ( #PCDATA )>
<!ELEMENT head-margin        ( #PCDATA )>
<!ELEMENT back-margin        ( #PCDATA )>
<!ELEMENT typeset-model      ( #PCDATA )>
<!ELEMENT issue-weight       ( #PCDATA )>
<!ELEMENT spine-width        ( #PCDATA )>

<!ELEMENT effect-cover-date  ( #PCDATA )>
<!ELEMENT cover-date         ( date-range )>
<!ELEMENT date-range         ( start-date, end-date? )>
<!ELEMENT start-date         ( #PCDATA )>
<!ELEMENT end-date           ( #PCDATA )>
<!ELEMENT cover-date-printed ( #PCDATA )>

<!ELEMENT special-issue      ( special-issue-id, full-name?,
                                conference?, editors? )>
<!ELEMENT special-issue-id   ( #PCDATA )>
<!ELEMENT full-name          ( #PCDATA )>

<!ELEMENT conference         ( abbr-name?, venue?,
                                ( effect-date, conference-date )?, sponsor? )>
<!ELEMENT abbr-name          ( #PCDATA )>
<!ELEMENT venue              ( #PCDATA )>
<!ELEMENT effect-date        ( #PCDATA )>
<!ELEMENT conference-date    ( date-range )>
<!ELEMENT sponsor            ( #PCDATA )>

<!ELEMENT editors            ( #PCDATA )>

<!ELEMENT no-pages-prelims   ( #PCDATA )>
<!ELEMENT no-pages-interior  ( #PCDATA )>
<!ELEMENT no-pages-extra     ( #PCDATA )>
<!ELEMENT no-pages-insert    ( #PCDATA )>
<!ELEMENT no-pages-bm        ( #PCDATA )>
<!ELEMENT no-pages-print     ( #PCDATA )>
<!ELEMENT no-pages-web       ( #PCDATA )>
<!ELEMENT no-pages-total     ( #PCDATA )>
<!ELEMENT no-pages-blank     ( #PCDATA )>
<!ELEMENT no-pages-adverts   ( #PCDATA )>

<!ELEMENT page-ranges        ( page-range+ )>
<!ELEMENT page-range         ( first-page, last-page )>
<!ATTLIST page-range 
           type                 %page-range-type;  #REQUIRED >
<!ELEMENT first-page         ( #PCDATA )>
<!ELEMENT last-page          ( #PCDATA )>

<!ELEMENT issue-content      ( row+ )>

<!ELEMENT row                ( version-no?, aid?, pii?, doi?,
                                 item-title,
                                copyright-status?, copyright-recd-date?,
                                corr-author?, pit?, prd-type?,
                                prefix?, suffix?, first-e-page?, last-e-page?,
                                page-from?, page-to?,
                                pdf-pages?, online-publ-date?,
                                online-version,
                                no-issues-free?, no-issues-paid?,
                                no-offprints-tot?, no-offprints-paid?,
                                no-offprints-free?, page-charge?, covers?, 
                                e-suite, no-colour-figs?, colour-fig-nr-print*,
                                remark? )>
<!ATTLIST row 
           type                 %row-type;  #REQUIRED >

<!ELEMENT prd-type           ( #PCDATA )>
<!ELEMENT prefix             ( #PCDATA )>
<!ELEMENT suffix             ( #PCDATA )>
<!ELEMENT first-e-page       ( #PCDATA )>
<!ELEMENT last-e-page        ( #PCDATA )>
<!ELEMENT page-from          ( #PCDATA )>
<!ELEMENT page-to            ( #PCDATA )>
<!ELEMENT pdf-pages          ( #PCDATA )>
<!ELEMENT online-publ-date   ( date )>
<!ELEMENT no-issues-free     ( #PCDATA )>
<!ELEMENT no-issues-paid     ( #PCDATA )>
<!ELEMENT no-offprints-tot   ( #PCDATA )>
<!ELEMENT no-offprints-paid  ( #PCDATA )>
<!ELEMENT no-offprints-free  ( #PCDATA )>
<!ELEMENT page-charge        ( #PCDATA )>
<!ELEMENT covers             ( #PCDATA )>
<!ELEMENT e-suite            ( #PCDATA )>
<!ELEMENT colour-fig-nr-print  ( #PCDATA )>

<!ELEMENT issue-remarks      ( issue-remark+ )>
<!ELEMENT issue-remark       ( remark-type, remark, response? )>

<!-- PRINT/BIND ORDER -->

<!ELEMENT print-bind-info    ( general-info, print-details, issue-content, issue-remarks? )>

<!ELEMENT print-details      ( no-copies, no-author-copies,
                                no-mark-prom-copies, no-voucher-copies, no-grace-copies,
                                no-extra-copies, total-print-run,
                                no-pages-cover, no-pages-coated, hold-despatch-date? )>

<!ELEMENT no-copies          ( #PCDATA )>
<!ELEMENT no-author-copies   ( #PCDATA )>
<!ELEMENT no-mark-prom-copies  ( #PCDATA )>
<!ELEMENT no-voucher-copies  ( #PCDATA )>
<!ELEMENT no-grace-copies    ( #PCDATA )>
<!ELEMENT no-extra-copies    ( #PCDATA )>
<!ELEMENT total-print-run    ( #PCDATA )>
<!ELEMENT no-pages-cover     ( #PCDATA )>
<!ELEMENT no-pages-coated    ( #PCDATA )>
<!ELEMENT hold-despatch-date ( date )>

<!-- ISSUE-LABELS ORDER -->

<!ELEMENT issue-labels-info  ( general-info, print-details, issue-labels-details,
                                issue-remarks? )>

<!ELEMENT issue-labels-details  ( issue-weight )>

=== DigiscapeNoida/.Net-Projects-/XML ORDER/dtd/WileyJ-Order.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE orders SYSTEM "WileyJ-Order.dtd">
<?xml-stylesheet type="text/xsl" href="WileyJ-Order.xsl" ?>
<orders>
  <order>
    <time day="18" month="04" yr="2008" hr="13" min="57" sec="49"/>
    <due-date><date day="02" month="05" yr="2008"/></due-date>
    <prod-site>Wiley-Blackwell Journals - US</prod-site>
    <stage step="S100"/>
    <executor type="TYPESETTER" addressee="yes">
      <exec-code>THOM</exec-code>
      <exec-name>Thomson Digital</exec-name>
      <aff>
        <address>B/10-12</address>
        <address-contd>Noida Special Economic Zone</address-contd>
        <zipcode zipcode-pos="AFTERCTY">201 305</zipcode>
        <cty>Noida</cty>
        <cny>India</cny>
        <tel>+91-120-256 2499</tel>
        <fax>+91-120-256 2299</fax>
      </aff>
    </executor>
    <item-info>
      <jid>BIT</jid>
	  <jname>Biotechnology and Bioengineering</jname>
      <aid>10569</aid>
      <pii>S0378-7753(08)00624-1</pii>
      <doi>10.1016/j.jpowsour.2008.03.060</doi>
      <item-title>Catalytic Activity of Cobalt Deposited on Nanostructured Poly(p-xylylene) Films
</item-title>
	  <editor-info>
		<editor>Dr. C.K. Dyer</editor>
		<designation></designation>
        <aff>
          <organization>Pennsylvania State University</organization>
          <institute>Catalytic Activity of Cobalt Deposited on Nanostructured</institute>
          <address>212 EES Bldg</address>
          <zipcode zipcode-pos="AFTERCTY">16802</zipcode>
          <cty>University Park, PA</cty>
          <cny>United States</cny>
          <tel>+1 8148632270</tel>
          <fax>+1 8148659974</fax>
          <ead>mdemirel@engr.psu.edu</ead>
        </aff>
	  </editor-info>
      <received-date><date day="01" month="02" yr="2008"/></received-date>
      <revised-date><date day="23" month="03" yr="2008"/></revised-date>
      <accept-date><date day="25" month="03" yr="2008"/></accept-date>
      <prd-type-as-sent>FTP</prd-type-as-sent>
      <online-version type="print"></online-version>
      <pit>SCO</pit>
      <no-mns-pages>14</no-mns-pages>
      <no-phys-figs>4</no-phys-figs>
      <no-bw-figs>2</no-bw-figs>
      <no-web-colour-figs>2</no-web-colour-figs>
      <no-colour-figs>0</no-colour-figs>
      <no-e-components>0</no-e-components>
      <physical-figures>
        <figure>
          <figure-nr>1</figure-nr>
          <figure-type>BW</figure-type>
        </figure>
        <figure>
          <figure-nr>2</figure-nr>
          <figure-type>BW</figure-type>
        </figure>
        <figure>
          <figure-nr>3</figure-nr>
          <figure-type>COLOUR</figure-type>
        </figure>
        <figure>
          <figure-nr>4</figure-nr>
          <figure-type>COLOUR</figure-type>
        </figure>
      </physical-figures>
      <righthand-start>N</righthand-start>
      <copyright-status>002</copyright-status>
          <copyright-recd-date><date day="26" month="03" yr="2008"/></copyright-recd-date>
      <first-author>
        <degree>Dr.</degree>
        <fnm>Niranjan</fnm>
        <snm>Malvadkar</snm>
      </first-author>
      <corr-author>
        <degree>Dr.</degree>
        <fnm>Melik C.</fnm>
        <snm>Demirel</snm>
        <aff>
          <organization>Pennsylvania State University</organization>
          <institute>Catalytic Activity of Cobalt Deposited on Nanostructured</institute>
          <address>212 EES Bldg</address>
          <zipcode zipcode-pos="AFTERCTY">16802</zipcode>
          <cty>University Park, PA</cty>
          <cny>United States</cny>
          <tel>+1 8148632270</tel>
          <fax>+1 8148659974</fax>
          <ead>mdemirel@engr.psu.edu</ead>
        </aff>
      </corr-author>
	  <eproofing-info>
		<to-mail>abcname@abc.com</to-mail>
		<cc-mail>xyzname@xyz.com</cc-mail>
		<cta>False</cta>
		<cid>False</cid>
		<offprint>False</offprint>
		<additional-attachments>None</additional-attachments>
	  </eproofing-info>
  <item-remarks>
    <item-remark>
        <remark-type>General</remark-type>
        <remark>Login : Colour Figs. 3,4</remark>
        <response></response>
    </item-remark>
  </item-remarks>
      <corrections type="MASTERFTP"/>
    </item-info>
  </order>
</orders>
